name: Parametric Diffusion 1D

on:
  push:
    paths: 
      - 'POD/ParametricDiffusion1D/**'
      - '!POD/ParametricDiffusion/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: Setup MPI
    #   uses: mpi4py/setup-mpi@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        build-essential \
        cmake \
        libboost-all-dev \
        libopenmpi-dev \
        libtrilinos-dev \
        wget
    
    - name: Cache Deal.II
      uses: actions/cache@v2
      with:
        path: '${{ runner.workspace }}/dealii_*.tar.gz'
        key: 'dealii-9.3.3'

    - name: Install Deal.II
      run: |
        wget https://github.com/dealii/dealii/releases/download/v9.3.3/dealii-9.3.3.tar.gz
        tar -xzf dealii-9.3.3.tar.gz
        mkdir dealii-9.3.3/build
        cd dealii-9.3.3/build
        cmake -D DEAL_II_WITH_PETSC=ON -D DEAL_II_WITH_SLEPC=ON -D DEAL_II_WITH_TRILINOS=ON ..
        make -j4
        sudo make install

    - name: Configure CMake
      working-directory: ./POD/ParametricDiffusion1D
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ./POD/ParametricDiffusion1D
      run: cmake --build ./build

    - name: Run test on parametric diffusion
      run: mpirun -n 4 ./build/ParametricDiffusion1D
