name: Parametric Diffusion 1D

on:
  push:
    paths: 
      - 'POD/ParametricDiffusion1D/**'
      - '!POD/ParametricDiffusion/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1

    # - name: Setup Python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.10.14'

    - name: Install boost
      uses: MarkusJx/install-boost@v2.4.5
      id: install-boost
      with:
        boost_version: 1.73.0

    - name: Configure CMake
      working-directory: ./POD/ParametricDiffusion1D
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

    - name: Build
      working-directory: ./POD/ParametricDiffusion1D
      run: cmake --build ./build

    - name: Run test on parametric diffusion
      run: mpirun -n 4 ./build/ParametricDiffusion1D
